pathToTarget: ./example/conf.d/
pathToTemplate: ./example/template/
template: template-main.conf
targetExtension: conf

values:
  php_bin: /usr/bin/php
  console: /srv/app/bin/console
  user: app
  autostart: true
  autorestart: true
  startretries: 3
  startsecs: 0
  numprocs: 1
  log_dir: /srv/app/var/log

configs:
  - name: worker-default
    values:
      command_args: queue:consume default

  - name: worker-shared-prefix
    template: template-fixed-log-prefix.conf
    values:
      command_args: queue:consume shared
      startsecs: 5
      log_prefix: shared-worker

  - name: worker-fixed-name
    template: template-fixed-log-name.conf
    values:
      command_args: queue:consume fixed-name
      startsecs: 2
      log_name: fixed-worker
