[program:worker-shared-prefix]
command=/usr/bin/python3 /srv/app/bin/worker.py consume shared
autostart=true
autorestart=true
startretries=3
startsecs=5
user=app
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/srv/app/var/log/shared-worker-stderr.log
stderr_logfile_maxbytes=10MB
stdout_logfile=/srv/app/var/log/shared-worker-stdout.log
stdout_logfile_maxbytes=10MB
