[program:{{ name }}]
command={{ python_bin }} {{ script }} {{ command_args }}
autostart={{ autostart | lower }}
autorestart={{ autorestart | lower }}
startretries={{ startretries }}
startsecs={{ startsecs }}
user={{ user }}
numprocs={{ numprocs }}
process_name=%(program_name)s_%(process_num)02d
stderr_logfile={{ log_dir }}/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stdout_logfile={{ log_dir }}/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB
